import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';
import Theme from '../constants/theme';

const { height, width } = Dimensions.get('window');

const spacing = {
  xsmall: 5,
  small: 10,
  medium: 15,
  large: 20,
  xlarge: 30,
};

const borderRadius = {
  small: 4,
  medium: 8,
  large: 10,
  xlarge: 20,
};

const borderWidth = {
  thin: 1,
  medium: 2,
  thick: 3,
};

const STATUS_BAR_HEIGHT = Platform.OS === 'ios' ? 20 : StatusBar.currentHeight;
const HEADER_HEIGHT = 50;
const NAVIGATION_BAR_HEIGHT = 45; // This can be adjusted based on your navigation bar height

export const styles = StyleSheet.create({
  subContainer: {
    display: 'flex',
    flex: 1,
  },
  fullScreenContainer: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  headerContainer: {
    position: 'absolute',
    top: STATUS_BAR_HEIGHT,
    left: 0,
    right: 0,
    height: HEADER_HEIGHT,
    width: '93%',
    marginHorizontal: '3.5%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
    zIndex: 1000,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
    overflow: 'hidden',
  },
  formCard: {
    width: '100%',
    height: '100%',
    borderColor: 'rgba(255, 255, 255, 0.3)',
    borderWidth: 1,
    borderRadius: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
  },
  headerUserContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerMenuIcon: {
    paddingLeft: 10,
  },
  userName: {
    color: Theme.colors.white,
    fontSize: 14,
    fontFamily: 'Poppins_Medium',
    right: -30,
  },
  overlayContainer: {
    position: 'absolute',
    top: STATUS_BAR_HEIGHT + HEADER_HEIGHT + 10,
    left: 0,
    right: 0,
    zIndex: 900,
  },
  userInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: 60,
    right: -30,
    textAlign: 'right',
  },
  searchWrapper: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: Theme.colors.primary,
    elevation: 10,
    backgroundColor: Theme.colors.white,
    borderWidth: 1,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  searchIcon: {
    paddingVertical: 10,
    marginLeft: 2, 
  },
  suggestionsContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: Theme.colors.white,
    borderRadius: 10,
    marginTop: 50,
    elevation: 5,
    maxHeight: 200,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    overflow: 'hidden',
  },
  suggestionItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.lightBlack,
  },
  suggestionText: {
    fontSize: 14,
    color: Theme.colors.black,
    fontFamily: 'Poppins_Regular',
  },
  returnButton: {
    position: 'absolute',
    bottom: 0,
    right: 20,
    backgroundColor: Theme.colors.primary,
    padding: 10,
    borderRadius: 25,
    elevation: 10,
    zIndex: 1000,
    borderWidth: 1,
    borderColor: Theme.colors.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  mapTypeButtonsContainer: {
    position: 'absolute',
  left: 20,
  right: 20,
  flexDirection: 'row',
  justifyContent: 'center',
  padding: 10,
  borderRadius: 15,
  zIndex: 1000,
  },
  mapTypeButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginHorizontal: 5,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  mapTypeButtonActive: {
    backgroundColor: '#FFFFFF',
    borderColor: Theme.colors.primary,
  },
  mapTypeButtonText: {
    fontSize: 14,
    color: Theme.colors.white,
    marginLeft: 6,
    fontFamily: 'Poppins_Regular',
  },
  mapTypeButtonTextActive: {
    color: Theme.colors.primary,
    fontFamily: 'Poppins_Regular',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalContainer: {
    backgroundColor: Theme.colors.lightBg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    alignItems: 'center',
    elevation: 20,
  },
  permissionDeniedHeader: {
    fontSize: 22,
    color: Theme.colors.black,
    textAlign: 'center',
    marginVertical: 10,
    fontFamily: 'Poppins_Bold',
  },
  permissionDeniedText: {
    color: Theme.colors.lightBlack,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Poppins_Regular',
  },
  permissionButtons: {
    flexDirection: 'column',
    width: '100%',
  },
  permissionDeniedContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    elevation: 5,
    marginTop: 20,
  },
  permissionDeniedContainerHeader: {
    fontSize: 18,
    color: Theme.colors.primary,
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'Poppins_SemiBold',
  },
  permissionDeniedContainerText: {
    fontSize: 14,
    color: Theme.colors.black,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Poppins_Regular',
  },
  retryButton: {
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: 'white',
    backgroundColor: Theme.colors.primary,
    width: '100%',
    marginBottom: 10,
  },
  retryButtonText: {
    fontSize: 14,
    color: Theme.colors.white,
    textAlign: 'center',
    fontFamily: 'Poppins_Regular',
  },
  closeButton: {
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: Theme.colors.primary,
    backgroundColor: 'transparent',
  },
  closeButtonText: {
    fontSize: 14,
    color: Theme.colors.primary,
    textAlign: 'center',
    fontFamily: 'Poppins_Regular',
  },
});