import { StyleSheet } from 'react-native';
import Theme from '../constants/theme';

export const styles = StyleSheet.create({
  gradientContainer: {
    flex: 1,
    borderRadius: 15,
  },
  container: {
    flex: 1,
    alignItems: 'center',
  },
  subContainer: {
    display: 'flex',
    flex: 1,
    alignItems: 'center',
  },
  backButton: {
    position: 'absolute',
    zIndex: 1,
    left: 0,
    top: 25,
    paddingTop: 10,
  },
  title: {
    fontSize: 26,
    color: '#14AFBC',
    textAlign: 'center',
    width: '100%',
    paddingTop: 20,
    fontFamily: 'Poppins_Medium',
  },
  formContainer: {
    width: 320,
    height: 400,
    marginVertical: 'auto',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 15,    
  },
  contentContainer: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
  },
  welcomeText: {
    fontSize: 40,
    textAlign: 'left',
    fontFamily: 'Poppins_Bold',
    color: Theme.colors.accent,
    paddingBottom: 30,
  },
  inputContainer: {
    width: 300,
    marginBottom: 15,
  },
  label: {
    fontSize: 14,
    fontFamily: 'Poppins_Bold',
    color: Theme.colors.primary,
    marginBottom: 5,
    alignSelf: 'flex-start',
  },
  input: {
    borderColor:'rgba(86, 82, 82, 0.24)',
    borderWidth: 2,
    borderRadius: 10,
    paddingLeft: 10,
    fontSize: 15,
    color: Theme.colors.lightBlack,
    backgroundColor: Theme.colors.white,
    fontFamily: 'Poppins_Regular',
    borderWidth: 1,
    elevation: 1,
    shadowColor: Theme.colors.black, // iOS shadow
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  passwordInput: {
    flex: 1,
    paddingRight: 40,
  },
  eyeIcon: {
    position: 'absolute',
    right: 10,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: Theme.colors.primary,
    paddingVertical: 10,
    borderRadius: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
  },
  disabledButton: {
    backgroundColor: '#A1D8D9',
  },
  buttonText: {
    textAlign: 'center',
    color: '#fff',
    fontFamily: 'Poppins_Regular',
    fontSize: 16,
  },
  recoverButton: {
    marginTop: 10,
    marginBottom: 10,
    alignSelf: 'flex-end',
  },
  recoverText: {
    color: '#FB3B9A',
    fontSize: 14,
    textDecorationLine: 'underline',
    fontFamily: 'Poppins_Regular',
  },
  termsContainer: {
    width: '100%',
    position: 'absolute',
    bottom: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  termsText: {
    textAlign: 'center',
    width: '80%',
    lineHeight: 22,
    fontSize: 12,
    color: Theme.colors.black,
    fontFamily: 'Poppins_Regular',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    width: 300,
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Poppins_Regular',
  },
  modalButton: {
    backgroundColor: '#14AFBC',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins_Regular',
  },
});